services:
  app:
    build: .
    container_name: app
    command: python3 test_module
    ports:
      - 1000:1000
    volumes:
      - .:/app
    environment:
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 1000