services:
  database:
    build: module-db/
    container_name: db
    networks:
      module:
        aliases:
          - database
  app:
    build: module-app/
    container_name: app
    ports:
      - 8080:8080
    networks:
      - module
    links:
      - "database"
    depends_on:
      - database
networks:
  module:
    driver: bridge