apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-deployment
  labels:
    app: play
spec:
  replicas: 6
  selector:
    matchLabels:
      app: play
  template:
    metadata:
      labels:
        app: play
    spec:
      containers:
      - name: play-flask
        image: adreasnow/python-test:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80