name: Upload Python Package

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            adreasnow/python-test-app:latest
            adreasnow/python-test-app:${{ github.sha }}

  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBERNETES_KUBECONFIG }}
  
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            kubernetes/app-deployment.yaml
            kubernetes/service.yaml
          images: |
            adreasnow/python-test-app:${{ github.sha }}
